# Generated by Django 5.2.4 on 2025-07-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=255, null=True)),
                ('Email', models.EmailField(max_length=255, null=True)),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='static\\staticE\\img')),
                ('SlideInfo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
