# Generated by Django 5.2.4 on 2025-07-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblinfo',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to='staticE\\img'),
        ),
    ]
