# Generated by Django 5.2.4 on 2025-07-16 04:09

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_tblinfo_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuName', models.CharField(max_length=255, null=True)),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubMenuName', models.CharField(max_length=255, null=True)),
                ('SubMenuDescription', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('MenuID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='accounts.tblmenu')),
            ],
        ),
    ]
