# Generated by Django 5.2.4 on 2025-07-19 16:34

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tblmenu_tblsubmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblmenu',
            name='Description',
        ),
        migrations.AddField(
            model_name='tblmenu',
            name='MenuDescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblsubmenu',
            name='MenuID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tblmenu'),
        ),
        migrations.AlterField(
            model_name='tblsubmenu',
            name='SubMenuDescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
