# Generated by Django 5.2.4 on 2025-07-19 17:26

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_tblmenu_description_tblmenu_menudescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblMenuDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('MenuID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tblsubmenu')),
            ],
        ),
    ]
