# Generated by Django 5.2.4 on 2025-07-19 17:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tblmenudetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FooterName', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblSubFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubFooterName', models.CharField(max_length=255, null=True)),
                ('SubFooterDescription', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
    ]
