# Generated by Django 5.2.4 on 2025-07-19 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tblfooter_tblsubfooter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsubfooter',
            name='FooterID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tblfooter'),
        ),
    ]
