# Generated by Django 5.2.4 on 2025-07-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tblsubfooter_footerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SlideName', models.CharField(max_length=255, null=True)),
                ('SlideImage', models.ImageField(blank=True, null=True, upload_to='staticE\\img')),
            ],
        ),
    ]
