# Generated by Django 5.2.4 on 2025-07-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tblslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblslide',
            name='SlideImage',
            field=models.ImageField(blank=True, null=True, upload_to='pic\\img'),
        ),
    ]
